import c3d from '../../../build/Release/c3d.node';
import Command from '../../command/Command';
import * as like from '../../commands/CommandLike';
import * as cmd from '../../commands/GeometryCommands';
import { Editor } from '../../editor/Editor';
import centerCircle from './img/center-circle.svg';
import centerEllipse from './img/center-ellipse.svg';
import centerPointArc from './img/center-point-arc.svg';
import centerRectangle from './img/center-rectangle.svg';
import characterCurve from './img/character-curve.svg';
import cornerRectangle from './img/corner-rectangle.svg';
import curve from './img/curve.svg';
import cut from './img/cut.svg';
import cylinder from './img/cylinder.svg';
import difference from './img/difference.svg';
import extrude from './img/extrude.svg';
import fillet from './img/fillet.svg';
import intersection from './img/intersection.svg';
import join from './img/join.svg';
import line from './img/line.svg';
import loft from './img/loft.svg';
import mirror from './img/mirror.svg';
import move from './img/move.svg';
import offsetFace from './img/offset-face.svg';
import radialArray from './img/radial-array.svg';
import regularPolygon from './img/regular-polygon.svg';
import { default as draftSolid, default as rotate } from './img/rotate.svg';
import scale from './img/scale.svg';
import sphere from './img/sphere.svg';
import spiral from './img/spiral.svg';
import threePointArc from './img/three-point-arc.svg';
import threePointCircle from './img/three-point-circle.svg';
import threePointEllipse from './img/three-point-ellipse.svg';
import threePointRectangle from './img/three-point-rectangle.svg';
import trim from './img/trim.svg';
import twoPointCircle from './img/two-point-circle.svg';
import { default as changePoint, default as union } from './img/union.svg';

export const icons = new Map<any, string>();
icons.set(cmd.MoveCommand, move);
icons.set(cmd.RotateCommand, rotate);
icons.set(cmd.ScaleCommand, scale);
icons.set(cmd.FilletSolidCommand, fillet);
icons.set(cmd.IntersectionCommand, intersection);
icons.set(cmd.DifferenceCommand, difference);
icons.set(cmd.UnionCommand, union);
icons.set(cmd.CutCommand, cut);
icons.set(cmd.OffsetFaceCommand, offsetFace);
icons.set(cmd.DraftSolidCommand, draftSolid);
icons.set(cmd.ActionFaceCommand, move);
icons.set(cmd.DeleteCommand, move);
icons.set(cmd.CurveCommand, curve);
icons.set(cmd.SphereCommand, sphere);
icons.set(cmd.CenterCircleCommand, centerCircle);
icons.set(cmd.TwoPointCircleCommand, twoPointCircle);
icons.set(cmd.ThreePointCircleCommand, threePointCircle);
icons.set(cmd.CenterPointArcCommand, centerPointArc);
icons.set(cmd.ThreePointArcCommand, threePointArc);
icons.set(cmd.CenterEllipseCommand, centerEllipse);
icons.set(cmd.ThreePointEllipseCommand, threePointEllipse);
icons.set(cmd.PolygonCommand, regularPolygon);
icons.set(cmd.LineCommand, line);
icons.set(cmd.ThreePointRectangleCommand, threePointRectangle);
icons.set(cmd.CornerRectangleCommand, cornerRectangle);
icons.set(cmd.CenterRectangleCommand, centerRectangle);
icons.set(cmd.CylinderCommand, cylinder);
icons.set(cmd.ThreePointBoxCommand, move);
icons.set(cmd.CornerBoxCommand, move);
icons.set(cmd.CenterBoxCommand, move);
icons.set(cmd.LoftCommand, loft);
icons.set(cmd.ExtrudeCommand, extrude);
icons.set(cmd.MirrorCommand, mirror);
icons.set(cmd.JoinCurvesCommand, join);
icons.set(cmd.SpiralCommand, spiral);
icons.set(cmd.CharacterCurveCommand, characterCurve);
// icons.set(cmd.MergerFaceCommand, offsetFace);
icons.set(cmd.TrimCommand, trim);
icons.set(cmd.OffsetCurveCommand, line);
icons.set(cmd.BridgeCurvesCommand, mirror);
icons.set(cmd.RevolutionCommand, line);
icons.set(cmd.ModifyContourCommand, changePoint);
icons.set(cmd.ShellCommand, changePoint);
icons.set(cmd.RadialArrayCommand, radialArray);
icons.set(cmd.ExtensionShellCommand, radialArray);
icons.set(cmd.DuplicateCommand, characterCurve);
icons.set(cmd.SlotCommand, characterCurve);

icons.set(c3d.ElementarySolid, move);
icons.set(c3d.FilletSolid, fillet);
icons.set(c3d.FaceModifiedSolid, offsetFace);
icons.set(c3d.BooleanSolid, union);
icons.set(c3d.CurveExtrusionSolid, extrude);
icons.set(c3d.ChamferSolid, fillet);
icons.set(c3d.TransformedSolid, move);
icons.set(c3d.SymmetrySolid, mirror);
icons.set(c3d.CuttingSolid, cut);
icons.set(c3d.DuplicationSolid, radialArray);

export const tooltips = new Map<typeof Command, string>();
tooltips.set(cmd.MoveCommand, "Move");
tooltips.set(cmd.RotateCommand, "Rotate");
tooltips.set(cmd.ScaleCommand, "Scale");
tooltips.set(cmd.FilletSolidCommand, "Fillet");
tooltips.set(cmd.IntersectionCommand, "Boolean intersection");
tooltips.set(cmd.DifferenceCommand, "Boolean difference");
tooltips.set(cmd.UnionCommand, "Boolean union");
tooltips.set(cmd.CutCommand, "Cut solid with curve");
tooltips.set(cmd.OffsetFaceCommand, "Offset face");
tooltips.set(cmd.DraftSolidCommand, "Draft solid");
tooltips.set(cmd.DeleteCommand, "Delete");
tooltips.set(cmd.ActionFaceCommand, "Move face");
tooltips.set(cmd.CurveCommand, "Curve");
tooltips.set(cmd.SphereCommand, "Sphere");
tooltips.set(cmd.CenterCircleCommand, "Center and radius circle");
tooltips.set(cmd.TwoPointCircleCommand, "Two-point circle");
tooltips.set(cmd.ThreePointCircleCommand, "Three-point circle");
tooltips.set(cmd.CenterPointArcCommand, "Center-point arc");
tooltips.set(cmd.ThreePointArcCommand, "Three-point arc");
tooltips.set(cmd.CenterEllipseCommand, "Center ellipse");
tooltips.set(cmd.ThreePointEllipseCommand, "Three-point ellipse");
tooltips.set(cmd.PolygonCommand, "Regular polygon");
tooltips.set(cmd.LineCommand, "Line");
tooltips.set(cmd.ThreePointRectangleCommand, "Three point rectangle");
tooltips.set(cmd.CornerRectangleCommand, "Corner rectangle");
tooltips.set(cmd.CenterRectangleCommand, "Center rectangle");
tooltips.set(cmd.CylinderCommand, "Cylinder");
tooltips.set(cmd.ThreePointBoxCommand, "Three point Box");
tooltips.set(cmd.CornerBoxCommand, "Corner box");
tooltips.set(cmd.CenterBoxCommand, "Center box");
tooltips.set(cmd.LoftCommand, "Loft");
tooltips.set(cmd.MirrorCommand, "Mirror");
tooltips.set(cmd.JoinCurvesCommand, "Join curves");
tooltips.set(cmd.ExtrudeCommand, "Extrude");
tooltips.set(cmd.SpiralCommand, "Spiral");
tooltips.set(cmd.CharacterCurveCommand, "Custom function");
tooltips.set(cmd.TrimCommand, "Cut off line segments at intersections of curves");
tooltips.set(cmd.OffsetCurveCommand, "Offset Loop");
tooltips.set(cmd.BridgeCurvesCommand, "Bridge two curves");
tooltips.set(cmd.RevolutionCommand, "Revolve");
tooltips.set(cmd.ModifyContourCommand, "ModifyCurve");
tooltips.set(cmd.ShellCommand, "Shell (thicken) solid or stroke (thicken) curve");
tooltips.set(cmd.RadialArrayCommand, "Radial array");
tooltips.set(cmd.ExtensionShellCommand, "Extend face");
tooltips.set(cmd.DuplicateCommand, "Duplicate object");
tooltips.set(cmd.SlotCommand, "Create a hole");

export const keybindings = new Map<string, string>();
keybindings.set("gizmo:move:x", "X axis");
keybindings.set("gizmo:move:y", "Y axis");
keybindings.set("gizmo:move:z", "Z axis");
keybindings.set("gizmo:move:xy", "Z plane");
keybindings.set("gizmo:move:yz", "X plane");
keybindings.set("gizmo:move:xz", "Y plane");
keybindings.set("gizmo:move:screen", "Screen space");
keybindings.set("gizmo:move:free", "Freestyle");
keybindings.set("gizmo:rotate:x", "X axis");
keybindings.set("gizmo:rotate:y", "Y axis");
keybindings.set("gizmo:rotate:z", "Z axis");
keybindings.set("gizmo:rotate:screen", "Screen space");
keybindings.set("gizmo:rotate:free", "Freestyle");
keybindings.set("gizmo:rotate:pivot", "Pivot");
keybindings.set("gizmo:scale:x", "X axis");
keybindings.set("gizmo:scale:y", "Y axis");
keybindings.set("gizmo:scale:z", "Z axis");
keybindings.set("gizmo:scale:xy", "Z plane");
keybindings.set("gizmo:scale:yz", "X plane");
keybindings.set("gizmo:scale:xz", "Y plane");
keybindings.set("gizmo:scale:xyz", "Uniform");
keybindings.set("gizmo:scale:free", "Freestyle");
keybindings.set("command:abort", "Abort");
keybindings.set("command:finish", "Finish");
keybindings.set("gizmo:curve:line-segment", "Line segment");
keybindings.set("gizmo:curve:arc", "Arc");
keybindings.set("gizmo:curve:polyline", "Polyline");
keybindings.set("gizmo:curve:nurbs", "NURBS");
keybindings.set("gizmo:curve:hermite", "Hermite");
keybindings.set("gizmo:curve:bezier", "Bezier");
keybindings.set("gizmo:curve:cubic-spline", "Cubic spline");
keybindings.set("gizmo:curve:undo", "Undo");
keybindings.set("gizmo:line:undo", "Undo");
keybindings.set("gizmo:fillet-solid:add", "Add variable fillet point");
keybindings.set("gizmo:fillet-solid:distance", "Distance");
keybindings.set("gizmo:fillet-solid:fillet", "Fillet distance");
keybindings.set("gizmo:fillet-solid:chamfer", "Chamfer distance");
keybindings.set("gizmo:fillet-solid:angle", "Chamfer angle");
keybindings.set("gizmo:circle:mode", "Toggle vertical/horizontal");
keybindings.set("gizmo:polygon:add-vertex", "Add a vertex");
keybindings.set("gizmo:polygon:subtract-vertex", "Subtract a vertex");
keybindings.set("gizmo:polygon:mode", "Toggle vertical/horizontal");
keybindings.set("gizmo:spiral:angle", "Angle");
keybindings.set("gizmo:spiral:radius", "Radius");
keybindings.set("gizmo:spiral:length", "Length");
keybindings.set("gizmo:extrude:race1", "Angle 1");
keybindings.set("gizmo:extrude:distance1", "Distance 1");
keybindings.set("gizmo:extrude:race2", "Angle 2");
keybindings.set("gizmo:extrude:distance2", "Distance 2");
keybindings.set("gizmo:extrude:thickness", "Thickness");
keybindings.set("gizmo:extrude:union", "Union");
keybindings.set("gizmo:extrude:difference", "Difference");
keybindings.set("gizmo:extrude:intersect", "Intersect");
keybindings.set("gizmo:extrude:new-body", "New body");
keybindings.set("gizmo:sphere:union", "Union");
keybindings.set("gizmo:sphere:difference", "Difference");
keybindings.set("gizmo:sphere:intersect", "Intersect");
keybindings.set("gizmo:sphere:new-body", "New body");
keybindings.set("gizmo:box:union", "Union");
keybindings.set("gizmo:box:difference", "Difference");
keybindings.set("gizmo:box:intersect", "Intersect");
keybindings.set("gizmo:box:new-body", "New body");
keybindings.set("gizmo:cylinder:union", "Union");
keybindings.set("gizmo:cylinder:difference", "Difference");
keybindings.set("gizmo:cylinder:intersect", "Intersect");
keybindings.set("gizmo:cylinder:new-body", "New body");
keybindings.set("gizmo:offset-face:distance", "Distance");
keybindings.set("gizmo:offset-face:angle", "Angle adjacent faces");
keybindings.set("gizmo:offset-face:toggle", "New body");
keybindings.set("gizmo:refillet-face:distance", "Distance");
keybindings.set("gizmo:mirror:x", "Positive X");
keybindings.set("gizmo:mirror:y", "Positive Y");
keybindings.set("gizmo:mirror:z", "Positive Z");
keybindings.set("gizmo:mirror:-x", "Negative X");
keybindings.set("gizmo:mirror:-y", "Negative Y");
keybindings.set("gizmo:mirror:-z", "Negative Z");
keybindings.set("gizmo:mirror:free", "Freestyle");
keybindings.set("gizmo:rebuild:forward", "Go forward in history");
keybindings.set("gizmo:rebuild:backward", "Go backward in history");
keybindings.set("gizmo:modify-contour:fillet-all", "Fillet all");
keybindings.set("gizmo:revolution:angle", "Revolution angle");
keybindings.set("gizmo:revolution:thickness", "Revolution thickness");
keybindings.set("gizmo:offset-curve:distance", "Offset distance");
keybindings.set("snaps:set-x", "X axis");
keybindings.set("snaps:set-y", "Y axis");
keybindings.set("snaps:set-z", "Z axis");
keybindings.set("snaps:set-normal", "Normal");
keybindings.set("snaps:set-binormal", "Binormal");
keybindings.set("snaps:set-tangent", "Tangent");
keybindings.set("snaps:set-square", "Square");
keybindings.set("gizmo:shell", "Thickness");

export default (editor: Editor): void => {
    for (const Command of Object.values(cmd)) {
        editor.registry.addOne('plasticity-viewport', `command:${Command.identifier}`, () => {
            const command = new Command(editor);
            command.agent = 'user';
            editor.enqueue(command);
        });
    }

    for (const Command of Object.values(like)) {
        editor.registry.addOne('plasticity-viewport', `command:${Command.identifier}`, () => {
            const command = new Command(editor);
            command.agent = 'user';
            editor.enqueue(command);
        });
    }
}
