import box from 'bootstrap-icons/icons/box.svg';
import trash from 'bootstrap-icons/icons/trash.svg';
import Command, * as cmd from '../../commands/Command';
import circle from './img/circle.svg';
import curve from './img/curve.svg';
import cut from './img/cut.svg';
import cylinder from './img/cylinder.svg';
import difference from './img/difference.svg';
import extrude from './img/extrude.svg';
import fillet from './img/fillet.svg';
import intersection from './img/intersection.svg';
import line from './img/line.svg';
import loft from './img/loft.svg';
import mirror from './img/mirror.svg';
import move from './img/move.svg';
import offsetFace from './img/offset-face.svg';
import rect from './img/rect.svg';
import { default as draftSolid, default as rotate } from './img/rotate.svg';
import scale from './img/scale.svg';
import sphere from './img/sphere.svg';
import union from './img/union.svg';

const icons = new Map<typeof Command, string>();
icons.set(cmd.MoveCommand, move);
icons.set(cmd.RotateCommand, rotate);
icons.set(cmd.ScaleCommand, scale);
icons.set(cmd.FilletCommand, fillet);
icons.set(cmd.IntersectionCommand, intersection);
icons.set(cmd.DifferenceCommand, difference);
icons.set(cmd.UnionCommand, union);
icons.set(cmd.CutCommand, cut);
icons.set(cmd.OffsetFaceCommand, offsetFace);
icons.set(cmd.DraftSolidCommand, draftSolid);
icons.set(cmd.RemoveFaceCommand, trash);
icons.set(cmd.CreateFaceCommand, offsetFace);
icons.set(cmd.ActionFaceCommand, move);
icons.set(cmd.FilletFaceCommand, fillet);
icons.set(cmd.PurifyFaceCommand, trash);
icons.set(cmd.CurveCommand, curve);
icons.set(cmd.SphereCommand, sphere);
icons.set(cmd.CircleCommand, circle);
icons.set(cmd.LineCommand, line);
icons.set(cmd.ThreePointRectangleCommand, rect);
icons.set(cmd.CornerRectangleCommand, rect);
icons.set(cmd.CylinderCommand, cylinder);
icons.set(cmd.BoxCommand, box);
icons.set(cmd.LoftCommand, loft);
icons.set(cmd.ExtrudeCommand, extrude);
icons.set(cmd.ExtrudeRegionCommand, extrude);
icons.set(cmd.MirrorCommand, mirror);
icons.set(cmd.JoinCurvesCommand, mirror);
icons.set(cmd.RegionCommand, mirror);
icons.set(cmd.RegionBooleanCommand, mirror);
// icons.set(cmd.MergerFaceCommand, offsetFace);

export default icons;